-- Remove all tables that were created
DROP TABLE IF EXISTS PRODUCT, CUSTOMER, ORDR, CART;

-- Create S table
CREATE TABLE PRODUCT (
    PID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    WEIGHT INT NOT NULL,
    PRICE DECIMAL(3,2) NOT NULL,
    RATING INT,
    QTY INT,
    DESCRIPT VARCHAR(255) NOT NULL
);

-- Show PRODUCT table
DESCRIBE PRODUCT;

CREATE TABLE CUSTOMER (
    USERID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    PHONE CHAR(10) NOT NULL,
    EMAIL VARCHAR(255),
    ADDR VARCHAR(255),
    BDAY DATE    
);

-- Show CUSTOMER table
DESCRIBE CUSTOMER;

-- Create SP table
CREATE TABLE ORDR (
    OID INT AUTO_INCREMENT,
    USERID INT,
    STATUS VARCHAR(20),
    PRIMARY KEY (OID,USERID),
    FOREIGN KEY (USERID) REFERENCES CUSTOMER(USERID)
);

-- Show ORDR table
DESCRIBE ORDR;
SHOW CREATE TABLE ORDR;

CREATE TABLE CART (
    OID INT AUTO_INCREMENT,
    PID INT,
    NUM INT NOT NULL,
    PRIMARY KEY (OID,PID),
    FOREIGN KEY (OID) REFERENCES ORDR(OID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID)
);

-- Show CART table
DESCRIBE CART;
SHOW CREATE TABLE CART;
