-- Remove all tables that were created
DROP TABLE IF EXISTS CART, WISH;
DROP TABLE IF EXISTS ORDR, SESS;
DROP TABLE IF EXISTS PRODUCT, CUSTOMER;

-- Create PRODUCT table
CREATE TABLE PRODUCT (
    PID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    WEIGHT INT NOT NULL DEFAULT 0,
    PRICE DECIMAL(6,2) NOT NULL DEFAULT 0,
    RATING DECIMAL(2,1) DEFAULT 0,
    QTY INT NOT NULL DEFAULT 0,
    DESCRIPT VARCHAR(255) NOT NULL
);

-- Show PRODUCT table
DESCRIBE PRODUCT;

CREATE TABLE CUSTOMER (
    USERID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(40) NOT NULL,
    PHONE CHAR(10) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ADDR VARCHAR(255),
    BDAY DATE,
    PASS CHAR(64) NOT NULL,
    EMP INT NOT NULL DEFAULT 0
);

-- Show CUSTOMER table
DESCRIBE CUSTOMER;

-- Create ORDR table
CREATE TABLE ORDR (
    OID INT AUTO_INCREMENT,
    USERID INT,
    STATUS VARCHAR(20),
    PRIMARY KEY (OID,USERID),
    FOREIGN KEY (USERID) REFERENCES CUSTOMER(USERID)
);

-- Show ORDR table
DESCRIBE ORDR;

CREATE TABLE CART (
    OID INT AUTO_INCREMENT,
    PID INT,
    NUM INT NOT NULL,
    PRIMARY KEY (OID,PID),
    FOREIGN KEY (OID) REFERENCES ORDR(OID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID)
);

-- Show CART table
DESCRIBE CART;


CREATE TABLE WISH (
    USERID INT,
    PID INT,
    NUM INT NOT NULL DEFAULT 1,
    PRIMARY KEY (USERID,PID),
    FOREIGN KEY (USERID) REFERENCES CUSTOMER(USERID),
    FOREIGN KEY (PID) REFERENCES PRODUCT(PID)
);

-- Show WISH table
DESCRIBE WISH;


CREATE TABLE SESS (
    USERID INT,
    SID CHAR(255),
    NUM INT NOT NULL DEFAULT 1,
    PRIMARY KEY (USERID,SID),
    FOREIGN KEY (USERID) REFERENCES CUSTOMER(USERID)
);

-- Show SESS table
DESCRIBE SESS;
